on:
  workflow_call:

jobs:
  # Release alpha version on NPM for Hive libraries
  npm:
    uses: the-guild-org/shared-config/.github/workflows/release-snapshot.yml@main
    with:
      npmTag: alpha
      buildScript: build:libraries
      nodeVersion: 18
      packageManager: pnpm
    secrets:
      githubToken: ${{ secrets.GITHUB_TOKEN }}
      npmToken: ${{ secrets.NPM_TOKEN }}

  # Upload zipped tarballs to GitHub
  cli-artifacts:
    runs-on: ubuntu-22.04

    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: setup environment
        uses: ./.github/actions/setup
        with:
          codegen: false # no need to run because release script will run it anyway
          actor: release-alpha
          cacheNext: false
          cacheTurbo: true

      - name: build libraries
        run: pnpm build:libraries

      # Needed for `oclif pack win`
      - name: Install NSIS
        run: |
          sudo apt-get -y install nsis

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: compile binaries
        working-directory: ./packages/libraries/cli
        run: pnpm compile

      - name: upload macos
        uses: actions/upload-artifact@v3
        with:
          name: hive-cli-macos
          path: ./packages/libraries/cli/binaries/hive-macos

      - name: upload linux
        uses: actions/upload-artifact@v3
        with:
          name: hive-cli-linux
          path: ./packages/libraries/cli/binaries/hive-linux

      - name: upload windows
        uses: actions/upload-artifact@v3
        with:
          name: hive-cli-windows
          path: ./packages/libraries/cli/binaries/hive-windows.exe

  cli-test:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    needs: [cli-artifacts]
    steps:
      - name: Pull artifact for macos
        if: matrix.os == 'macos-latest'
        uses: actions/download-artifact@v3
        with:
          name: hive-cli-macos

      - name: Pull artifact for ubuntu
        if: matrix.os == 'ubuntu-latest'
        uses: actions/download-artifact@v3
        with:
          name: hive-cli-linux

      # - name: Pull artifact for windows
      #   if: matrix.os == 'windows-latest'
      #   uses: actions/download-artifact@v3
      #   with:
      #     name: hive-cli-windows

      - name: Unzip and run
        run: |
          rm -rf /usr/local/bin/node
          rm -rf /usr/local/lib/node

          if command -v node &> /dev/null
          then
              echo "Expected node to not be installed"
              command -v node
              exit 1
          fi

      - name: Run on MacOS
        if: matrix.os == 'macos-latest'
        run: ./hive-macos --version || exit 1

      - name: Run on Linux
        if: matrix.os == 'ubuntu-latest'
        run: ./hive-linux --version || exit 1
